/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesRpoRouteImport } from './routes/services/rpo'
import { Route as ServicesResumeSourcingRouteImport } from './routes/services/resume-sourcing'
import { Route as ServicesDirectHireRouteImport } from './routes/services/direct-hire'
import { Route as AuthenticatedDashboardShellRouteImport } from './routes/_authenticated/_dashboard-shell'
import { Route as AuthenticatedDashboardShellUsersRouteImport } from './routes/_authenticated/_dashboard-shell/users'
import { Route as AuthenticatedDashboardShellSettingsRouteImport } from './routes/_authenticated/_dashboard-shell/settings'
import { Route as AuthenticatedDashboardShellRolesRouteImport } from './routes/_authenticated/_dashboard-shell/roles'
import { Route as AuthenticatedDashboardShellProspectsRouteImport } from './routes/_authenticated/_dashboard-shell/prospects'
import { Route as AuthenticatedDashboardShellProspectDatabaseRouteImport } from './routes/_authenticated/_dashboard-shell/prospect-database'
import { Route as AuthenticatedDashboardShellProspectDashboardRouteImport } from './routes/_authenticated/_dashboard-shell/prospect-dashboard'
import { Route as AuthenticatedDashboardShellJobsRouteImport } from './routes/_authenticated/_dashboard-shell/jobs'
import { Route as AuthenticatedDashboardShellJobRequestsRouteImport } from './routes/_authenticated/_dashboard-shell/job-requests'
import { Route as AuthenticatedDashboardShellInvoicesRouteImport } from './routes/_authenticated/_dashboard-shell/invoices'
import { Route as AuthenticatedDashboardShellInterviewsRouteImport } from './routes/_authenticated/_dashboard-shell/interviews'
import { Route as AuthenticatedDashboardShellHeroProfileRouteImport } from './routes/_authenticated/_dashboard-shell/hero-profile'
import { Route as AuthenticatedDashboardShellHeroDashboardRouteImport } from './routes/_authenticated/_dashboard-shell/hero-dashboard'
import { Route as AuthenticatedDashboardShellDashboardRouteImport } from './routes/_authenticated/_dashboard-shell/dashboard'
import { Route as AuthenticatedDashboardShellContractsRouteImport } from './routes/_authenticated/_dashboard-shell/contracts'
import { Route as AuthenticatedDashboardShellClientsRouteImport } from './routes/_authenticated/_dashboard-shell/clients'
import { Route as AuthenticatedDashboardShellClientDashboardRouteImport } from './routes/_authenticated/_dashboard-shell/client-dashboard'
import { Route as AuthenticatedDashboardShellHeroesIndexRouteImport } from './routes/_authenticated/_dashboard-shell/heroes.index'
import { Route as AuthenticatedDashboardShellHeroesIdRouteImport } from './routes/_authenticated/_dashboard-shell/heroes.$id'
import { Route as AuthenticatedDashboardShellCompaniesIdRouteImport } from './routes/_authenticated/_dashboard-shell/companies.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRpoRoute = ServicesRpoRouteImport.update({
  id: '/services/rpo',
  path: '/services/rpo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesResumeSourcingRoute = ServicesResumeSourcingRouteImport.update({
  id: '/services/resume-sourcing',
  path: '/services/resume-sourcing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDirectHireRoute = ServicesDirectHireRouteImport.update({
  id: '/services/direct-hire',
  path: '/services/direct-hire',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardShellRoute =
  AuthenticatedDashboardShellRouteImport.update({
    id: '/_dashboard-shell',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardShellUsersRoute =
  AuthenticatedDashboardShellUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedDashboardShellRoute,
  } as any)
const AuthenticatedDashboardShellSettingsRoute =
  AuthenticatedDashboardShellSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardShellRoute,
  } as any)
const AuthenticatedDashboardShellRolesRoute =
  AuthenticatedDashboardShellRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => AuthenticatedDashboardShellRoute,
  } as any)
const AuthenticatedDashboardShellProspectsRoute =
  AuthenticatedDashboardShellProspectsRouteImport.update({
    id: '/prospects',
    path: '/prospects',
    getParentRoute: () => AuthenticatedDashboardShellRoute,
  } as any)
const AuthenticatedDashboardShellProspectDatabaseRoute =
  AuthenticatedDashboardShellProspectDatabaseRouteImport.update({
    id: '/prospect-database',
    path: '/prospect-database',
    getParentRoute: () => AuthenticatedDashboardShellRoute,
  } as any)
const AuthenticatedDashboardShellProspectDashboardRoute =
  AuthenticatedDashboardShellProspectDashboardRouteImport.update({
    id: '/prospect-dashboard',
    path: '/prospect-dashboard',
    getParentRoute: () => AuthenticatedDashboardShellRoute,
  } as any)
const AuthenticatedDashboardShellJobsRoute =
  AuthenticatedDashboardShellJobsRouteImport.update({
    id: '/jobs',
    path: '/jobs',
    getParentRoute: () => AuthenticatedDashboardShellRoute,
  } as any)
const AuthenticatedDashboardShellJobRequestsRoute =
  AuthenticatedDashboardShellJobRequestsRouteImport.update({
    id: '/job-requests',
    path: '/job-requests',
    getParentRoute: () => AuthenticatedDashboardShellRoute,
  } as any)
const AuthenticatedDashboardShellInvoicesRoute =
  AuthenticatedDashboardShellInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedDashboardShellRoute,
  } as any)
const AuthenticatedDashboardShellInterviewsRoute =
  AuthenticatedDashboardShellInterviewsRouteImport.update({
    id: '/interviews',
    path: '/interviews',
    getParentRoute: () => AuthenticatedDashboardShellRoute,
  } as any)
const AuthenticatedDashboardShellHeroProfileRoute =
  AuthenticatedDashboardShellHeroProfileRouteImport.update({
    id: '/hero-profile',
    path: '/hero-profile',
    getParentRoute: () => AuthenticatedDashboardShellRoute,
  } as any)
const AuthenticatedDashboardShellHeroDashboardRoute =
  AuthenticatedDashboardShellHeroDashboardRouteImport.update({
    id: '/hero-dashboard',
    path: '/hero-dashboard',
    getParentRoute: () => AuthenticatedDashboardShellRoute,
  } as any)
const AuthenticatedDashboardShellDashboardRoute =
  AuthenticatedDashboardShellDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedDashboardShellRoute,
  } as any)
const AuthenticatedDashboardShellContractsRoute =
  AuthenticatedDashboardShellContractsRouteImport.update({
    id: '/contracts',
    path: '/contracts',
    getParentRoute: () => AuthenticatedDashboardShellRoute,
  } as any)
const AuthenticatedDashboardShellClientsRoute =
  AuthenticatedDashboardShellClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedDashboardShellRoute,
  } as any)
const AuthenticatedDashboardShellClientDashboardRoute =
  AuthenticatedDashboardShellClientDashboardRouteImport.update({
    id: '/client-dashboard',
    path: '/client-dashboard',
    getParentRoute: () => AuthenticatedDashboardShellRoute,
  } as any)
const AuthenticatedDashboardShellHeroesIndexRoute =
  AuthenticatedDashboardShellHeroesIndexRouteImport.update({
    id: '/heroes/',
    path: '/heroes/',
    getParentRoute: () => AuthenticatedDashboardShellRoute,
  } as any)
const AuthenticatedDashboardShellHeroesIdRoute =
  AuthenticatedDashboardShellHeroesIdRouteImport.update({
    id: '/heroes/$id',
    path: '/heroes/$id',
    getParentRoute: () => AuthenticatedDashboardShellRoute,
  } as any)
const AuthenticatedDashboardShellCompaniesIdRoute =
  AuthenticatedDashboardShellCompaniesIdRouteImport.update({
    id: '/companies/$id',
    path: '/companies/$id',
    getParentRoute: () => AuthenticatedDashboardShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/services/direct-hire': typeof ServicesDirectHireRoute
  '/services/resume-sourcing': typeof ServicesResumeSourcingRoute
  '/services/rpo': typeof ServicesRpoRoute
  '/client-dashboard': typeof AuthenticatedDashboardShellClientDashboardRoute
  '/clients': typeof AuthenticatedDashboardShellClientsRoute
  '/contracts': typeof AuthenticatedDashboardShellContractsRoute
  '/dashboard': typeof AuthenticatedDashboardShellDashboardRoute
  '/hero-dashboard': typeof AuthenticatedDashboardShellHeroDashboardRoute
  '/hero-profile': typeof AuthenticatedDashboardShellHeroProfileRoute
  '/interviews': typeof AuthenticatedDashboardShellInterviewsRoute
  '/invoices': typeof AuthenticatedDashboardShellInvoicesRoute
  '/job-requests': typeof AuthenticatedDashboardShellJobRequestsRoute
  '/jobs': typeof AuthenticatedDashboardShellJobsRoute
  '/prospect-dashboard': typeof AuthenticatedDashboardShellProspectDashboardRoute
  '/prospect-database': typeof AuthenticatedDashboardShellProspectDatabaseRoute
  '/prospects': typeof AuthenticatedDashboardShellProspectsRoute
  '/roles': typeof AuthenticatedDashboardShellRolesRoute
  '/settings': typeof AuthenticatedDashboardShellSettingsRoute
  '/users': typeof AuthenticatedDashboardShellUsersRoute
  '/companies/$id': typeof AuthenticatedDashboardShellCompaniesIdRoute
  '/heroes/$id': typeof AuthenticatedDashboardShellHeroesIdRoute
  '/heroes/': typeof AuthenticatedDashboardShellHeroesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/services/direct-hire': typeof ServicesDirectHireRoute
  '/services/resume-sourcing': typeof ServicesResumeSourcingRoute
  '/services/rpo': typeof ServicesRpoRoute
  '/client-dashboard': typeof AuthenticatedDashboardShellClientDashboardRoute
  '/clients': typeof AuthenticatedDashboardShellClientsRoute
  '/contracts': typeof AuthenticatedDashboardShellContractsRoute
  '/dashboard': typeof AuthenticatedDashboardShellDashboardRoute
  '/hero-dashboard': typeof AuthenticatedDashboardShellHeroDashboardRoute
  '/hero-profile': typeof AuthenticatedDashboardShellHeroProfileRoute
  '/interviews': typeof AuthenticatedDashboardShellInterviewsRoute
  '/invoices': typeof AuthenticatedDashboardShellInvoicesRoute
  '/job-requests': typeof AuthenticatedDashboardShellJobRequestsRoute
  '/jobs': typeof AuthenticatedDashboardShellJobsRoute
  '/prospect-dashboard': typeof AuthenticatedDashboardShellProspectDashboardRoute
  '/prospect-database': typeof AuthenticatedDashboardShellProspectDatabaseRoute
  '/prospects': typeof AuthenticatedDashboardShellProspectsRoute
  '/roles': typeof AuthenticatedDashboardShellRolesRoute
  '/settings': typeof AuthenticatedDashboardShellSettingsRoute
  '/users': typeof AuthenticatedDashboardShellUsersRoute
  '/companies/$id': typeof AuthenticatedDashboardShellCompaniesIdRoute
  '/heroes/$id': typeof AuthenticatedDashboardShellHeroesIdRoute
  '/heroes': typeof AuthenticatedDashboardShellHeroesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/careers': typeof CareersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/_authenticated/_dashboard-shell': typeof AuthenticatedDashboardShellRouteWithChildren
  '/services/direct-hire': typeof ServicesDirectHireRoute
  '/services/resume-sourcing': typeof ServicesResumeSourcingRoute
  '/services/rpo': typeof ServicesRpoRoute
  '/_authenticated/_dashboard-shell/client-dashboard': typeof AuthenticatedDashboardShellClientDashboardRoute
  '/_authenticated/_dashboard-shell/clients': typeof AuthenticatedDashboardShellClientsRoute
  '/_authenticated/_dashboard-shell/contracts': typeof AuthenticatedDashboardShellContractsRoute
  '/_authenticated/_dashboard-shell/dashboard': typeof AuthenticatedDashboardShellDashboardRoute
  '/_authenticated/_dashboard-shell/hero-dashboard': typeof AuthenticatedDashboardShellHeroDashboardRoute
  '/_authenticated/_dashboard-shell/hero-profile': typeof AuthenticatedDashboardShellHeroProfileRoute
  '/_authenticated/_dashboard-shell/interviews': typeof AuthenticatedDashboardShellInterviewsRoute
  '/_authenticated/_dashboard-shell/invoices': typeof AuthenticatedDashboardShellInvoicesRoute
  '/_authenticated/_dashboard-shell/job-requests': typeof AuthenticatedDashboardShellJobRequestsRoute
  '/_authenticated/_dashboard-shell/jobs': typeof AuthenticatedDashboardShellJobsRoute
  '/_authenticated/_dashboard-shell/prospect-dashboard': typeof AuthenticatedDashboardShellProspectDashboardRoute
  '/_authenticated/_dashboard-shell/prospect-database': typeof AuthenticatedDashboardShellProspectDatabaseRoute
  '/_authenticated/_dashboard-shell/prospects': typeof AuthenticatedDashboardShellProspectsRoute
  '/_authenticated/_dashboard-shell/roles': typeof AuthenticatedDashboardShellRolesRoute
  '/_authenticated/_dashboard-shell/settings': typeof AuthenticatedDashboardShellSettingsRoute
  '/_authenticated/_dashboard-shell/users': typeof AuthenticatedDashboardShellUsersRoute
  '/_authenticated/_dashboard-shell/companies/$id': typeof AuthenticatedDashboardShellCompaniesIdRoute
  '/_authenticated/_dashboard-shell/heroes/$id': typeof AuthenticatedDashboardShellHeroesIdRoute
  '/_authenticated/_dashboard-shell/heroes/': typeof AuthenticatedDashboardShellHeroesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/careers'
    | '/how-it-works'
    | '/industries'
    | '/login'
    | '/services/direct-hire'
    | '/services/resume-sourcing'
    | '/services/rpo'
    | '/client-dashboard'
    | '/clients'
    | '/contracts'
    | '/dashboard'
    | '/hero-dashboard'
    | '/hero-profile'
    | '/interviews'
    | '/invoices'
    | '/job-requests'
    | '/jobs'
    | '/prospect-dashboard'
    | '/prospect-database'
    | '/prospects'
    | '/roles'
    | '/settings'
    | '/users'
    | '/companies/$id'
    | '/heroes/$id'
    | '/heroes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/careers'
    | '/how-it-works'
    | '/industries'
    | '/login'
    | '/services/direct-hire'
    | '/services/resume-sourcing'
    | '/services/rpo'
    | '/client-dashboard'
    | '/clients'
    | '/contracts'
    | '/dashboard'
    | '/hero-dashboard'
    | '/hero-profile'
    | '/interviews'
    | '/invoices'
    | '/job-requests'
    | '/jobs'
    | '/prospect-dashboard'
    | '/prospect-database'
    | '/prospects'
    | '/roles'
    | '/settings'
    | '/users'
    | '/companies/$id'
    | '/heroes/$id'
    | '/heroes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/careers'
    | '/how-it-works'
    | '/industries'
    | '/login'
    | '/_authenticated/_dashboard-shell'
    | '/services/direct-hire'
    | '/services/resume-sourcing'
    | '/services/rpo'
    | '/_authenticated/_dashboard-shell/client-dashboard'
    | '/_authenticated/_dashboard-shell/clients'
    | '/_authenticated/_dashboard-shell/contracts'
    | '/_authenticated/_dashboard-shell/dashboard'
    | '/_authenticated/_dashboard-shell/hero-dashboard'
    | '/_authenticated/_dashboard-shell/hero-profile'
    | '/_authenticated/_dashboard-shell/interviews'
    | '/_authenticated/_dashboard-shell/invoices'
    | '/_authenticated/_dashboard-shell/job-requests'
    | '/_authenticated/_dashboard-shell/jobs'
    | '/_authenticated/_dashboard-shell/prospect-dashboard'
    | '/_authenticated/_dashboard-shell/prospect-database'
    | '/_authenticated/_dashboard-shell/prospects'
    | '/_authenticated/_dashboard-shell/roles'
    | '/_authenticated/_dashboard-shell/settings'
    | '/_authenticated/_dashboard-shell/users'
    | '/_authenticated/_dashboard-shell/companies/$id'
    | '/_authenticated/_dashboard-shell/heroes/$id'
    | '/_authenticated/_dashboard-shell/heroes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CareersRoute: typeof CareersRoute
  HowItWorksRoute: typeof HowItWorksRoute
  IndustriesRoute: typeof IndustriesRoute
  LoginRoute: typeof LoginRoute
  ServicesDirectHireRoute: typeof ServicesDirectHireRoute
  ServicesResumeSourcingRoute: typeof ServicesResumeSourcingRoute
  ServicesRpoRoute: typeof ServicesRpoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/rpo': {
      id: '/services/rpo'
      path: '/services/rpo'
      fullPath: '/services/rpo'
      preLoaderRoute: typeof ServicesRpoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/resume-sourcing': {
      id: '/services/resume-sourcing'
      path: '/services/resume-sourcing'
      fullPath: '/services/resume-sourcing'
      preLoaderRoute: typeof ServicesResumeSourcingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/direct-hire': {
      id: '/services/direct-hire'
      path: '/services/direct-hire'
      fullPath: '/services/direct-hire'
      preLoaderRoute: typeof ServicesDirectHireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_dashboard-shell': {
      id: '/_authenticated/_dashboard-shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedDashboardShellRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_dashboard-shell/users': {
      id: '/_authenticated/_dashboard-shell/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedDashboardShellUsersRouteImport
      parentRoute: typeof AuthenticatedDashboardShellRoute
    }
    '/_authenticated/_dashboard-shell/settings': {
      id: '/_authenticated/_dashboard-shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedDashboardShellSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardShellRoute
    }
    '/_authenticated/_dashboard-shell/roles': {
      id: '/_authenticated/_dashboard-shell/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedDashboardShellRolesRouteImport
      parentRoute: typeof AuthenticatedDashboardShellRoute
    }
    '/_authenticated/_dashboard-shell/prospects': {
      id: '/_authenticated/_dashboard-shell/prospects'
      path: '/prospects'
      fullPath: '/prospects'
      preLoaderRoute: typeof AuthenticatedDashboardShellProspectsRouteImport
      parentRoute: typeof AuthenticatedDashboardShellRoute
    }
    '/_authenticated/_dashboard-shell/prospect-database': {
      id: '/_authenticated/_dashboard-shell/prospect-database'
      path: '/prospect-database'
      fullPath: '/prospect-database'
      preLoaderRoute: typeof AuthenticatedDashboardShellProspectDatabaseRouteImport
      parentRoute: typeof AuthenticatedDashboardShellRoute
    }
    '/_authenticated/_dashboard-shell/prospect-dashboard': {
      id: '/_authenticated/_dashboard-shell/prospect-dashboard'
      path: '/prospect-dashboard'
      fullPath: '/prospect-dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardShellProspectDashboardRouteImport
      parentRoute: typeof AuthenticatedDashboardShellRoute
    }
    '/_authenticated/_dashboard-shell/jobs': {
      id: '/_authenticated/_dashboard-shell/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedDashboardShellJobsRouteImport
      parentRoute: typeof AuthenticatedDashboardShellRoute
    }
    '/_authenticated/_dashboard-shell/job-requests': {
      id: '/_authenticated/_dashboard-shell/job-requests'
      path: '/job-requests'
      fullPath: '/job-requests'
      preLoaderRoute: typeof AuthenticatedDashboardShellJobRequestsRouteImport
      parentRoute: typeof AuthenticatedDashboardShellRoute
    }
    '/_authenticated/_dashboard-shell/invoices': {
      id: '/_authenticated/_dashboard-shell/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedDashboardShellInvoicesRouteImport
      parentRoute: typeof AuthenticatedDashboardShellRoute
    }
    '/_authenticated/_dashboard-shell/interviews': {
      id: '/_authenticated/_dashboard-shell/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof AuthenticatedDashboardShellInterviewsRouteImport
      parentRoute: typeof AuthenticatedDashboardShellRoute
    }
    '/_authenticated/_dashboard-shell/hero-profile': {
      id: '/_authenticated/_dashboard-shell/hero-profile'
      path: '/hero-profile'
      fullPath: '/hero-profile'
      preLoaderRoute: typeof AuthenticatedDashboardShellHeroProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardShellRoute
    }
    '/_authenticated/_dashboard-shell/hero-dashboard': {
      id: '/_authenticated/_dashboard-shell/hero-dashboard'
      path: '/hero-dashboard'
      fullPath: '/hero-dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardShellHeroDashboardRouteImport
      parentRoute: typeof AuthenticatedDashboardShellRoute
    }
    '/_authenticated/_dashboard-shell/dashboard': {
      id: '/_authenticated/_dashboard-shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardShellDashboardRouteImport
      parentRoute: typeof AuthenticatedDashboardShellRoute
    }
    '/_authenticated/_dashboard-shell/contracts': {
      id: '/_authenticated/_dashboard-shell/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AuthenticatedDashboardShellContractsRouteImport
      parentRoute: typeof AuthenticatedDashboardShellRoute
    }
    '/_authenticated/_dashboard-shell/clients': {
      id: '/_authenticated/_dashboard-shell/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedDashboardShellClientsRouteImport
      parentRoute: typeof AuthenticatedDashboardShellRoute
    }
    '/_authenticated/_dashboard-shell/client-dashboard': {
      id: '/_authenticated/_dashboard-shell/client-dashboard'
      path: '/client-dashboard'
      fullPath: '/client-dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardShellClientDashboardRouteImport
      parentRoute: typeof AuthenticatedDashboardShellRoute
    }
    '/_authenticated/_dashboard-shell/heroes/': {
      id: '/_authenticated/_dashboard-shell/heroes/'
      path: '/heroes'
      fullPath: '/heroes/'
      preLoaderRoute: typeof AuthenticatedDashboardShellHeroesIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardShellRoute
    }
    '/_authenticated/_dashboard-shell/heroes/$id': {
      id: '/_authenticated/_dashboard-shell/heroes/$id'
      path: '/heroes/$id'
      fullPath: '/heroes/$id'
      preLoaderRoute: typeof AuthenticatedDashboardShellHeroesIdRouteImport
      parentRoute: typeof AuthenticatedDashboardShellRoute
    }
    '/_authenticated/_dashboard-shell/companies/$id': {
      id: '/_authenticated/_dashboard-shell/companies/$id'
      path: '/companies/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof AuthenticatedDashboardShellCompaniesIdRouteImport
      parentRoute: typeof AuthenticatedDashboardShellRoute
    }
  }
}

interface AuthenticatedDashboardShellRouteChildren {
  AuthenticatedDashboardShellClientDashboardRoute: typeof AuthenticatedDashboardShellClientDashboardRoute
  AuthenticatedDashboardShellClientsRoute: typeof AuthenticatedDashboardShellClientsRoute
  AuthenticatedDashboardShellContractsRoute: typeof AuthenticatedDashboardShellContractsRoute
  AuthenticatedDashboardShellDashboardRoute: typeof AuthenticatedDashboardShellDashboardRoute
  AuthenticatedDashboardShellHeroDashboardRoute: typeof AuthenticatedDashboardShellHeroDashboardRoute
  AuthenticatedDashboardShellHeroProfileRoute: typeof AuthenticatedDashboardShellHeroProfileRoute
  AuthenticatedDashboardShellInterviewsRoute: typeof AuthenticatedDashboardShellInterviewsRoute
  AuthenticatedDashboardShellInvoicesRoute: typeof AuthenticatedDashboardShellInvoicesRoute
  AuthenticatedDashboardShellJobRequestsRoute: typeof AuthenticatedDashboardShellJobRequestsRoute
  AuthenticatedDashboardShellJobsRoute: typeof AuthenticatedDashboardShellJobsRoute
  AuthenticatedDashboardShellProspectDashboardRoute: typeof AuthenticatedDashboardShellProspectDashboardRoute
  AuthenticatedDashboardShellProspectDatabaseRoute: typeof AuthenticatedDashboardShellProspectDatabaseRoute
  AuthenticatedDashboardShellProspectsRoute: typeof AuthenticatedDashboardShellProspectsRoute
  AuthenticatedDashboardShellRolesRoute: typeof AuthenticatedDashboardShellRolesRoute
  AuthenticatedDashboardShellSettingsRoute: typeof AuthenticatedDashboardShellSettingsRoute
  AuthenticatedDashboardShellUsersRoute: typeof AuthenticatedDashboardShellUsersRoute
  AuthenticatedDashboardShellCompaniesIdRoute: typeof AuthenticatedDashboardShellCompaniesIdRoute
  AuthenticatedDashboardShellHeroesIdRoute: typeof AuthenticatedDashboardShellHeroesIdRoute
  AuthenticatedDashboardShellHeroesIndexRoute: typeof AuthenticatedDashboardShellHeroesIndexRoute
}

const AuthenticatedDashboardShellRouteChildren: AuthenticatedDashboardShellRouteChildren =
  {
    AuthenticatedDashboardShellClientDashboardRoute:
      AuthenticatedDashboardShellClientDashboardRoute,
    AuthenticatedDashboardShellClientsRoute:
      AuthenticatedDashboardShellClientsRoute,
    AuthenticatedDashboardShellContractsRoute:
      AuthenticatedDashboardShellContractsRoute,
    AuthenticatedDashboardShellDashboardRoute:
      AuthenticatedDashboardShellDashboardRoute,
    AuthenticatedDashboardShellHeroDashboardRoute:
      AuthenticatedDashboardShellHeroDashboardRoute,
    AuthenticatedDashboardShellHeroProfileRoute:
      AuthenticatedDashboardShellHeroProfileRoute,
    AuthenticatedDashboardShellInterviewsRoute:
      AuthenticatedDashboardShellInterviewsRoute,
    AuthenticatedDashboardShellInvoicesRoute:
      AuthenticatedDashboardShellInvoicesRoute,
    AuthenticatedDashboardShellJobRequestsRoute:
      AuthenticatedDashboardShellJobRequestsRoute,
    AuthenticatedDashboardShellJobsRoute: AuthenticatedDashboardShellJobsRoute,
    AuthenticatedDashboardShellProspectDashboardRoute:
      AuthenticatedDashboardShellProspectDashboardRoute,
    AuthenticatedDashboardShellProspectDatabaseRoute:
      AuthenticatedDashboardShellProspectDatabaseRoute,
    AuthenticatedDashboardShellProspectsRoute:
      AuthenticatedDashboardShellProspectsRoute,
    AuthenticatedDashboardShellRolesRoute:
      AuthenticatedDashboardShellRolesRoute,
    AuthenticatedDashboardShellSettingsRoute:
      AuthenticatedDashboardShellSettingsRoute,
    AuthenticatedDashboardShellUsersRoute:
      AuthenticatedDashboardShellUsersRoute,
    AuthenticatedDashboardShellCompaniesIdRoute:
      AuthenticatedDashboardShellCompaniesIdRoute,
    AuthenticatedDashboardShellHeroesIdRoute:
      AuthenticatedDashboardShellHeroesIdRoute,
    AuthenticatedDashboardShellHeroesIndexRoute:
      AuthenticatedDashboardShellHeroesIndexRoute,
  }

const AuthenticatedDashboardShellRouteWithChildren =
  AuthenticatedDashboardShellRoute._addFileChildren(
    AuthenticatedDashboardShellRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardShellRoute: typeof AuthenticatedDashboardShellRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardShellRoute:
    AuthenticatedDashboardShellRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CareersRoute: CareersRoute,
  HowItWorksRoute: HowItWorksRoute,
  IndustriesRoute: IndustriesRoute,
  LoginRoute: LoginRoute,
  ServicesDirectHireRoute: ServicesDirectHireRoute,
  ServicesResumeSourcingRoute: ServicesResumeSourcingRoute,
  ServicesRpoRoute: ServicesRpoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
