import { MigrationInterface, QueryRunner } from 'typeorm';

// Recruiter: full CRUD on prospects, interviews, invoices, companies, jobs, job-requests
// Heroes: read-only (heroes:read only — no create/update/delete)
// Contracts: removed (auto-generated by the system, not manually managed)
// Settings/Roles/Users: not included (admin-only)
export class AlignRecruiterPermissions1781720000000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `UPDATE "roles" SET "permissions" = '["dashboard","prospects","heroes:read","interviews","invoices","companies","jobs","job-requests"]' WHERE "id" = 2`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `UPDATE "roles" SET "permissions" = '["dashboard","prospects","heroes","contracts","invoices","interviews","jobs","job-requests"]' WHERE "id" = 2`,
    );
  }
}
